.TH rarstatus 1 "25 April 2026" "1.0" "rarstatus manual"
.SH NAME
rarstatus \- modern reimplementation of slstatus 
.SH SYNOPSIS
.B rarstatus
[\fI-v\fR] [\fI-h\fR] [\fI-1\fR]
.SH DESCRIPTION
.B rarstatus
is a utility to show system information in a "status bar" look.
It works similar to slstatus, but without bloat.
.SH OPTIONS
.TP
.B \-v
Print version information.
.TP
.B \-h
Print usage information.
.TP
.B \-1
Print status bar one time.
.SH AUTHOR
Written by rar.
